version: "3.9"
services:

  db:
    container_name: nedrex-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_DATABASE: reposcape
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: reposcaper
      MYSQL_PASSWORD: repotrial
    volumes:
      - nedrex-db-volume:/var/lib/mysql
    cap_add:
      - SYS_NICE
  server:
    container_name: nedrex-server
    image: andimajore/nedrex_repo:server
    depends_on:
      - "db"
    volumes:
      - nedrex-cache-volume:/etc/data/db
      - nedrex-usr-volume:/etc/data/usr
    expose:
      - 8090
    ports:
      - "8090:8090"
    restart: on-failure

  web:
    container_name: nedrex-web
    image: andimajore/nedrex_repo:web
    depends_on:
      - "server"
    ports:
      - "8080:8080"
    restart: on-failure
volumes:
  nedrex-db-volume:
  nedrex-usr-volume:
  nedrex-cache-volume:
